---
kind: Namespace
apiVersion: v1
metadata:
  name: mysql-persistent
  labels:
    app: mysql
---
apiVersion: v1
kind: Secret
metadata:
  name: mysql
  namespace: mysql-persistent
  labels:
    app: mysql
stringData:
  database-name: MYSQL_DATABASE
  database-password: MYSQL_PASSWORD
  database-root-password: MYSQL_ROOT_PASSWORD
  database-user: MYSQL_USER
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    template.openshift.io/expose-uri: mysql://{.spec.clusterIP}:{.spec.ports[?(.name=="mysql")].port}
  name: mysql
  namespace: mysql-persistent
  labels:
    app: mysql
spec:
  ports:
  - name: mysql
    port: 3306
  selector:
    name: mysql
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql
  namespace: mysql-persistent
  labels:
    app: mysql
spec:
  accessModes:
  - ReadWriteMany
  storageClassName: "INSERT_CORRECT_STORAGE_CLASS_HERE"
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: Deployment
metadata:
  annotations:
    template.alpha.openshift.io/wait-for-ready: 'true'
  name: mysql
  namespace: mysql-persistent
  labels:
    app: mysql
spec:
  replicas: 1
  selector:
    matchLabels:
      name: mysql
  template:
    metadata:
      annotations:
        backup.velero.io/backup-volumes: mysql-data
      labels:
        name: mysql
        app: mysql
    spec:
      containers:
      - env:
        - name: MYSQL_USER
          valueFrom:
            secretKeyRef:
              key: database-user
              name: mysql
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              key: database-password
              name: mysql
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              key: database-root-password
              name: mysql
        - name: MYSQL_DATABASE
          valueFrom:
            secretKeyRef:
              key: database-name
              name: mysql
        image: "registry.redhat.io/rhel8/mysql-80"
        imagePullPolicy: IfNotPresent
        name: mysql
        ports:
        - containerPort: 3306
        resources:
          limits:
            memory: 512Mi
        volumeMounts:
        - mountPath: "/var/lib/mysql/data"
          name: mysql-data
      volumes:
      - name: mysql-data
        persistentVolumeClaim:
          claimName: mysql
