---
- name: Import openshift-backup-infra install playbook
  import_playbook: playbooks/openshift-backup-infra/install.yaml
  when: uninstall is not defined

- name: Import openshift-backup-infra uninstall playbook
  import_playbook: playbooks/openshift-backup-infra/uninstall.yaml
  when: uninstall is defined
