---
- name: Import etcd playbook
  import_playbook: playbooks/etcd-backup/config.yaml
  when: "lookup('env', 'deploy_etcd') | bool"

- name: Import backup-infra-setup playbook
  import_playbook: playbooks/openshift-backup-infra-setup/config.yaml
  when: "lookup('env', 'deploy_backup_infra') | bool"
