- name: Copy noobaa-operator script to {{ noobaa_operator_tmp.path }}
  copy:
    src: 'files/{{ item }}'
    dest: '{{ noobaa_operator_tmp.path }}/{{ item }}'
    mode: a+x
  loop:
    - noobaa

- name: Uninstall Noobaa
  shell: "({{ noobaa_operator_tmp.path }}/noobaa uninstall --cleanup=true -n {{ noobaa_operator_namespace }} &)"
  register: noobaa_teardown
  ignore_errors: yes

# get rid of finalizers and locked resources